//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int IdEmp { get; set; }
        public Nullable<int> idDept { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
    
        public virtual Departements Departements { get; set; }
    }
}
